name: psuedo-irradience
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - xarray
  - zarr
  - numcodecs
  - pytorch
  - torchvision
  - torchdata
  - cartopy
  - rioxarray
  - pytorch-cuda==11.6
pip:
  - huggingface_hub
  - einops