name: satip
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - numpy==1.23.0
  - pandas>=1.1.4
  - requests
  - fsspec
  - satpy==0.36.0
  - zarr
  - xarray
  - bottleneck
  - tqdm
  - matplotlib
  - cartopy
pip:
  # The conda version of imagecodecs doesn't currently include libjxl,
  # which is required for JPEG-XL compression. So we must install using pip:
  - imagecodecs
  - eumdac
